//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace informator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipes
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public int CookingTime { get; set; }
        public string Ingredients { get; set; }
        public string Instructions { get; set; }
    }
}
